name: Run Python Tests

on: 
  push:  
  pull_request:  

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Installiere Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Führe den Test Runner aus
        run: python playground/sampleproject/testrunner.py && echo $?
